urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from . import views
urlpatterns = [
    path('hello',views.hello_world),
    path('task',views.task),
    path('',views.home_page),
    path('analytics',views.analytics),
    path('<slug:customname>',views.redirect_url)
    path('delete/<int:pk>', views.HistoryDelete.as_view(), name='history_delete'),
    path('', views.HistoryList.as_view(), name='history'),
]

models.py
from django.db import models

# Create your models here.
class LongToShort(models.Model):
    long_url=models.URLField(max_length = 500)
    custom_name = models.CharField(max_length = 50, unique = True)
    created_date = models.DateField(auto_now_add = True)
    visit_count = models.IntegerField(default = 0)

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.conf import settings

from .signals import object_viewed_signal

User = settings.AUTH_USER_MODEL


class History(models.Model):
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    content_type    = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True) # product, post
    object_id       = models.PositiveIntegerField() # 1,2,3
    content_object  = GenericForeignKey() # is the actual object
    viewed_on       = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s viewed: %s" %(self.content_object, self.viewed_on)

    class Meta:
        verbose_name_plural = "Histories"

def object_viewed_receiver(sender, instance, request, *args, **kwargs):
    new_history = History.objects.create(
        user    = request.user,
        content_type    = ContentType.objects.get_for_model(sender),
        object_id      = instance.id,
    )

object_viewed_signal.connect(object_viewed_receiver)

views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import ListView, View
from django.views.generic.detail import SingleObjectMixin


from .models import LongToShort
from .models import History

# Create your views here.
def hello_world(request):
    return HttpResponse("Helllo how are you!!")

def task(request):
    context={"year":"2023","attendees":["Adi","Rishabh","Nikesh","sarthak"]}

    return render(request,"task.html",context)

def home_page(request):
    context={
        "submitted": False,
        "error": False
    }
    print(request.META)
    if request.method=="POST":
        #print(request.POST)
        data=request.POST
        
        longurl=data['longurl']
        customname=data['custom_name']

        try:
            context["long_url"]=longurl
            context["custom_name"]=request.build_absolute_uri()  + customname
            #customname=request.build_absolute_uri()  + customname
            obj=LongToShort(long_url=longurl,custom_name=customname)
            obj.save()
            context["submitted"]=True
            context["date"]=obj.created_date
            context["clicks"]=obj.visit_count
            #print(long_url,custom_name)
        except:
            context["error"]=True
            
    else:
        print("USer didn't submit yet")
    return render(request,"index.html",context)



def redirect_url(request,customname):
    row=LongToShort.objects.filter(custom_name=customname)
    print(row)
    if len(row)==0:
        return HttpResponse("This endpoint dosen't exist Error!!")
    obj=row[0]
    long_url=obj.long_url
    obj.visit_count+=1
    obj.save()
    return redirect(long_url)


def analytics(request):
    rows=LongToShort.objects.all()
    context={
        "rows":rows
    }
    return render(request,"analytics.html",context)

class HistoryList(ListView):
    def get_queryset(self):
        user_history = History.objects.filter(user=self.request.user)
        return user_history


class HistoryDelete(SingleObjectMixin, View):
    model = History
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj is not None:
            obj.delete()
        return redirect('history')

templates/analytics.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>Custom URL Shortener</title>

	<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" media="screen">
	<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" media="screen">
</head>

<body class="pace-done lout_stats30">
	<main id="content" role="main" class="wyniki wyniki_all">
		<div class="container">
			<div class="row">
				<div class="col-12 page_log_in mt-0">
					<h2 class="h1" style="text-align: center;">All Links Analytics</h2>
				</div>

				{% for obj in rows %}

				<div class="url_options url_stats_o" id="1">
					<p class="data_link">{{ obj.created_date }}</p>
					<p class="url_link">
						{{ obj.long_url }}
					</p>
					<p id="link" class="link_element">
						<a href="/redirect/{{ obj.custom_name }}" class="short_url_l" target="blank">
							{{ obj.custom_name }}</a>
					</p>
					<div class="stats_total btn-cutt click_stats btn_norm">
						<div>Total clicks <strong class="allClicks">{{ obj.visit_count }}</strong></div>
					</div>
				</div>

				{% endfor %}

			</div>
		</div>
	</main>

</body>

</html>

templates/history_lists.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}
<div class="container">
    <h2>History Page</h2>

        <div class="row">
            <div class="col-12">
                <table class="table">
                <thead>
                <tr>
                    <th scope="col">Page</th>
                    <th scope="col">Viewed On</th>
                    <th scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>

                {% for history in history_list %}
                    <tr>
                        <td>{{ history.content_object }}</td>
                        <td>{{ history.viewed_on|naturaltime }}</td>
                        <td><a href="{% url 'history_delete' history.pk  %}" class="btn btn-danger">Delete</a></td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>
            </div>
        </div>  
</div>  

{% endblock content %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>Custom URL Shortener</title>

	<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" media="screen">
	<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" media="screen">
</head>

<body class="pace-done is_index_lout">
	<main id="content" role="main">
		<section class="container-fluid mx-0 bg_cuttly_main_092021">
			<div class="header__bg"></div>
			<div class="mb-0">
				<div class="container position-relative">
					<div class="row">
						<div class="dv_main col-md-6 cutt_main_b2">
							<h2 class="h1">URL Shortener</h2>
							<h3 class="h2 h2_index text-left text-white">All the features you need in one place. <br />
								Shorten, manage and track your links the easy way.</h3>
							<div class="butt_on mx-auto">
								<a href="#shorten" class="btn_m_l btn_m_l_1">Shorten</a>
								<a href="/analytics" class="btn_m_l btn_m_r" target="_new">Analytics</a>
							</div>
						</div>
						<div class="col-md-6 mobile_bg text-right">
							<img src="{% static 'R.png' %}" />
						</div>
					</div>
				</div>
			</div>
		</section>

		<section class="bg_main" id="shorten" style="padding-bottom: 5%;">
			<div class="container cutt_main_inp">
				<div class="row">
					<div class="col-12 mt-4 py-2 mb-2">
						<form method="post" id="form_input">
							{% csrf_token %}
							<div class="input-group">
								<input type="url" class="cutt_url w-50 p-4 rounded-12"
									placeholder="Paste long url and shorten it" name="longurl" required />

								<input type="text" class="cutt_url w-25 p-4 rounded-12" placeholder="alias"
									name="custom_name" style="margin-left: 5%;" />

								<button class="btn_cutt rounded-6 shortenit_b" role="button">Shorten</button>
							</div>
						</form>
					</div>
				</div>


				{% if error %}		
				<div class="row">
					<div class="col-12 mt-4 py-2 mb-2" style="text-align: center; color: red;">
						<p>The alias name is already taken</p>
					</div>
				</div>
				{% endif %}



			</div>



			{% if submitted %}
			<div id="results">
				<div class="container">
					<div class="row py-4">
						<div class="col-12 result">
							<div class="url_options rounded-6" id="0">
								<p class="data_link">{{date}}</p>
								<p class="url_link">
									{{long_url}}

								</p>
								<p id="link" class="link_element">
									<a href="{{custom_name}}" class="short_url_l" target="_blank">{{custom_name}}</a>
								</p>
								<button class="btn-cutt i_s" onclick="copyToClipboard()" data-toggle="tooltip"
									data-html="true" data-placement="top" title="" data-original-title="Copy">
									<img src="{% static 'copy-icon.png' %}" />
								</button>
								<a href="/analytics/cc-ranklist" class="btn-cutt click_stats">
									<svg class="i_svg" viewBox="0 0 24 24">
										<use xlink:href="#i_chart"></use>
									</svg>
									<span>
										<b class="badge">{{clicks}}</b>clicks
									</span>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endif %}



			<div class="container" id="alert-box" style="display: none">
				<div class="row py-4">
					<div class="col-9"></div>
					<div class="col-3">
						<div class="alert alert-success">
							<strong>Copied to clipboard!</strong>
						</div>
					</div>
				</div>
			</div>
		</section>

		<footer class="footer-area footer--light">
			<div class="mini-footer">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="copyright-text">
								<p><a href="https://www.o1codingclub.in/">O(1) Coding Club</a></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
	</main>

	<script type="text/javascript">
		function copyToClipboard() {
			const element = document.getElementById("link");
			console.log(element.innerText);

			const el = document.createElement('textarea');
			el.value = element.innerText;
			el.setAttribute('readonly', '');
			el.style.position = 'absolute';
			el.style.left = '-9999px';
			document.body.appendChild(el);
			const selected =
			document.getSelection().rangeCount > 0
			? document.getSelection().getRangeAt(0)
			: false;
			el.select();
			document.execCommand('copy');
			document.body.removeChild(el);

			document.getElementById("alert-box").style.display = "block"
			setTimeout(() => {
				document.getElementById("alert-box").style.display = "none"
			}, 1500);
			;
		}
	</script>
</body>

</html>

templates/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>I am attending Django Workshop {{ year }}</h1>
    {% for i in attendees %}
        <h1>{{i}}</h1>
    {% endfor %}

</body>
</html>